// 阅读模式文章数据
window.readingArticles = [
  {
    id: 1,
    title: "Animal Picnic",
    category: "animal",
    titleChinese: "动物野餐",
    content: "One sunny day,  Giraffe  and  Panda  went to the park. \"Hello,  Tiger !\" said  Giraffe . \"Hello,  Bear ! Hello,  Wolf !\" said  Panda . They all sat under a big tree.\n\n Hippo  brought water, and  Crocodile  brought apples.  Lizard  and  Snake  played in the grass, while  Spider  made a web. In the air,  Ladybug ,  Dragonfly ,  Fly , and  Mosquito  flew happily.  Bee  sang, \"Buzz, buzz!\" and  Birdie  sang, too.\n\n By the bowl,  Goldfish  swam in circles.  Tadpole  jumped with  Frog .  Caterpillar  ate a leaf, and  Butterfly  danced. On the ground,  Ants  walked in a line, and  Snail  moved slowly.  Turtle  said, \"Hello, friends!\" Nearby,  Hamster  and  Guinea Pig  ate carrots, while  Mouse  ate cheese.\n\n On the farm,  Cow  said, \"Moo!\",  Horse  said, \"Neigh!\", and  Sheep  said, \"Baa!\"  Pig  said, \"Oink!\",  Chicken  said, \"Cluck, cluck!\",  Duck  said, \"Quack, quack!\",  Goose  said, \"Honk, honk!\", and  Pigeon  said, \"Coo, coo!\"\n\n All the  animals  were happy. They ate, they played, they sang. It was a big, happy picnic! 🧺😊",
    keyWords: ["Giraffe", "Panda", "Tiger", "Bear", "Wolf", "Hippo", "Crocodile", "Lizard", "Snake", "Spider", "Ladybug", "Dragonfly", "Fly", "Mosquito", "Bee", "Birdie", "Goldfish", "Tadpole", "Frog", "Caterpillar", "Butterfly", "Ants", "Snail", "Turtle", "Hamster", "Guinea Pig", "Mouse", "Cow", "Horse", "Sheep", "Pig", "Chicken", "Duck", "Goose", "Pigeon", "animals"]
  },
  {
    id: 5,
    title: "Baby's Colorful Day",
    category: "color",
    titleChinese: "宝宝的多彩一天",
    content: "Good morning, baby! Wake up, wake up! The Sun is shining bright. What color is the Sun? It's [Yellow]!\n\nLook out the window. The sky is [Blue], and there are [White] clouds. Oh, a bird with [Red] feathers is flying by! How many birds do you see? [One], [two], [three] birds!\n\nIt's time to get dressed. What color shirt do you want? The [Green] one or the [Purple] one? Let's wear the [Green] shirt with [Brown] pants. Put on your [Black] shoes too!\n\nBreakfast is ready! We have [Orange] juice, [White] milk, and [Yellow] eggs. Yummy! How many eggs would you like? [One] egg, please!\n\nAfter breakfast, let's play outside. The weather is [Sunny] and [Warm]. Let's count the flowers in the garden. There are [Five] [Red] roses, [Three] [Pink] tulips, and [Two] [Purple] lavender. So beautiful!\n\nIt's getting hot. Let's go inside. What's the temperature? It's [Thirty] degrees! Let's drink some cold water. Splash, splash! Water is [Blue] and wet.\n\nLunchtime! We have [Red] tomatoes, [Green] lettuce, and [Yellow] corn. Let's make a salad with [Five] vegetables. How many do you want? [Two] tomatoes, please!\n\nIn the afternoon, let's draw a picture. Use the [Red] crayon for the sun, [Blue] for the sky, [Green] for the grass, and [Brown] for the tree. Draw [Three] [Yellow] flowers and [Two] [Pink] butterflies. You're so [Smart]!\n\nThe sky is getting [Gray]. Oh, it's going to rain! Let's watch the [Rain] from the window. Listen to the pitter-patter. The ground is getting wet.\n\nDinnertime! We have [Orange] carrots, [White] rice, and [Red] apples for dessert. How many apples do we have? [Ten] apples! Let's eat [One] each.\n\nBefore bed, let's read a story. The book has [Colorful] pictures of [Animals]. Look at the [Brown] bear, [Gray] elephant, and [Black] cat. What a fun day! You feel [Happy] and [Tired]. Good night, baby! Sleep tight! 😴🌈",
    keyWords: ["Red", "Blue", "Yellow", "Green", "Purple", "Orange", "Pink", "Black", "White", "Gray", "Brown", "One", "Two", "Three", "Five", "Ten", "Thirty", "Sun", "Cloud", "Rain", "Sunny", "Warm", "Wake", "Dressed", "Eat", "Play", "Count", "Draw", "Drink", "Splash", "Read", "Happy", "Smart", "Tired", "Colorful", "Animals"]
  },
  {
    id: 6,
    title: "Happy Family Day",
    category: "family",
    titleChinese: "快乐的家庭日",
    content: "Today is Family Day! Baby, let's see who's in our family.\n\nThis is my [Father] (爸爸) and my [Mother] (妈妈). They love me very much! I have a [Brother] (兄弟) and a [Sister] (姐妹). We play together every day.\n\nLook at the photo on the wall. That's my [Grandfather] (祖父) and [Grandmother] (祖母). They give me candy when I visit them. I also have [Uncle] (叔叔) and [Aunt] (阿姨) who bring me toys.\n\nToday is a [Sunny] day. Let's [Run], [Jump], and [Play] in the park. [Father] will [Push] me on the swing, and [Mother] will take pictures. [Brother] will [Climb] the slide, and [Sister] will [Draw] a picture.\n\nIt's lunchtime! Let's have a picnic. We have [Bread], [Milk], [Apple], and [Egg]. [Mother] will [Give] me a big hug. [Father] will [Smile] and say, \"Yummy!\"\n\nIn the afternoon, let's go to [Grandmother]'s house. She will make delicious cookies for us. [Grandfather] will tell us stories about when he was young. We will [Laugh] and [Sing] together.\n\nWhat a [Happy] day! I love my [Family] very much. We are all [Kind] and [Friendly] to each other. I feel [Loved] and [Calm]. I am so lucky to have such a wonderful family! 💖👪",
    keyWords: ["Father", "Mother", "Brother", "Sister", "Grandfather", "Grandmother", "Uncle", "Aunt", "Family", "Sunny", "Run", "Jump", "Play", "Push", "Climb", "Draw", "Give", "Smile", "Laugh", "Sing", "Happy", "Kind", "Friendly", "Loved", "Calm", "Bread", "Milk", "Apple", "Egg"]
  },
  {
    id: 5,
    title: "Baby's Colorful Day",
    category: "color",
    titleChinese: "宝宝的多彩一天",
    content: "Good morning, baby! Wake up, wake up! The Sun is shining bright. What color is the Sun? It's [Yellow]!\n\nLook out the window. The sky is [Blue], and there are [White] clouds. Oh, a bird with [Red] feathers is flying by! How many birds do you see? [One], [two], [three] birds!\n\nIt's time to get dressed. What color shirt do you want? The [Green] one or the [Purple] one? Let's wear the [Green] shirt with [Brown] pants. Put on your [Black] shoes too!\n\nBreakfast is ready! We have [Orange] juice, [White] milk, and [Yellow] eggs. Yummy! How many eggs would you like? [One] egg, please!\n\nAfter breakfast, let's play outside. The weather is [Sunny] and [Warm]. Let's count the flowers in the garden. There are [Five] [Red] roses, [Three] [Pink] tulips, and [Two] [Purple] lavender. So beautiful!\n\nIt's getting hot. Let's go inside. What's the temperature? It's [Thirty] degrees! Let's drink some cold water. Splash, splash! Water is [Blue] and wet.\n\nLunchtime! We have [Red] tomatoes, [Green] lettuce, and [Yellow] corn. Let's make a salad with [Five] vegetables. How many do you want? [Two] tomatoes, please!\n\nIn the afternoon, let's draw a picture. Use the [Red] crayon for the sun, [Blue] for the sky, [Green] for the grass, and [Brown] for the tree. Draw [Three] [Yellow] flowers and [Two] [Pink] butterflies. You're so [Smart]!\n\nThe sky is getting [Gray]. Oh, it's going to rain! Let's watch the [Rain] from the window. Listen to the pitter-patter. The ground is getting wet.\n\nDinnertime! We have [Orange] carrots, [White] rice, and [Red] apples for dessert. How many apples do we have? [Ten] apples! Let's eat [One] each.\n\nBefore bed, let's read a story. The book has [Colorful] pictures of [Animals]. Look at the [Brown] bear, [Gray] elephant, and [Black] cat. What a fun day! You feel [Happy] and [Tired]. Good night, baby! Sleep tight! 😴🌈",
    keyWords: ["Red", "Blue", "Yellow", "Green", "Purple", "Orange", "Pink", "Black", "White", "Gray", "Brown", "One", "Two", "Three", "Five", "Ten", "Thirty", "Sun", "Cloud", "Rain", "Sunny", "Warm", "Wake", "Dressed", "Eat", "Play", "Count", "Draw", "Drink", "Splash", "Read", "Happy", "Smart", "Tired", "Colorful", "Animals"]
  },
  {
    id: 2,
    title: "Baby's Delicious Day",
    category: "food",
    titleChinese: "宝宝的美味一天",
    content: "Good morning, baby! Wake up, wake up! It's time for breakfast. What do we have? We have soft  Bread  and warm  Milk . Yummy, yummy! Let's eat an  Egg  too. It's good for you. Then we can have a little  Cake  as a sweet treat.\n\n After playing, it's lunchtime! Look, there's fluffy  Rice  on the plate. We have tasty  Chicken  and fresh  Fish  too. Let's sip some hot  Soup —it's so warm. Do you want a bite of  Cheese ? It's creamy and nice.\n\n In the afternoon, let's have a snack. Here are crispy  Cookies  and sweet  Candy . We can drink cold  Juice  or smooth  Yogurt . Oh, and there's cold  Ice Cream  too—so cool and sweet!\n\n Evening comes, it's dinner time. We have juicy  Beef  and tender  Pork . Let's eat some  Salad  with fresh veggies. For drinks, we can have  Water  or  Milk Tea . After dinner, we can share a small piece of  Chocolate —yum!\n\n What a happy day with lots of delicious food! Baby, can you say the names of the food?  Bread ,  Milk ,  Egg ... Let's learn together!",
    keyWords: ["Bread", "Milk", "Egg", "Cake", "Rice", "Chicken", "Fish", "Soup", "Cheese", "Cookies", "Candy", "Juice", "Yogurt", "Ice Cream", "Beef", "Pork", "Salad", "Water", "Milk Tea", "Chocolate"]
  },
  {
    id: 3,
    title: "A Happy Fruit Party",
    category: "fruit",
    titleChinese: "快乐的水果派对",
    content: "Hi, little baby! Today is a sunny day. We are having a happy fruit party! Look, so many fruits are here!\n\n This is a red Apple. \"Apple, Apple,\" crunchy and sweet. Yum yum!\n\n That is an Orange. \"Orange, Orange,\" round and bright. It tastes juicy!\n\n Look at the yellow Banana. \"Banana, Banana,\" long and curved. Peel it and eat!\n\n Here are purple Grapes. \"Grape, Grape,\" small and cute. One by one!\n\n Red Strawberries are here too. \"Strawberry, Strawberry,\" with tiny seeds. So lovely!\n\n Big Watermelon is on the table. \"Watermelon, Watermelon,\" green outside, red inside. Cool and sweet!\n\n Pink Peach is so soft. \"Peach, Peach,\" fuzzy and nice. Take a bite!\n\n Yellow Pear is here. \"Pear, Pear,\" smooth and yummy. We all like it!\n\n Spiky Pineapple comes. \"Pineapple, Pineapple,\" yellow inside. So tasty!\n\n Brown Kiwi has green flesh. \"Kiwi, Kiwi,\" with black seeds. Delicious!\n\n Orange Mango is sweet. \"Mango, Mango,\" soft and juicy. Yummy in the tummy!\n\n Red Lychee is small. \"Lychee, Lychee,\" with a bumpy skin. Sweet inside!\n\n Brown Longan is here. \"Longan, Longan,\" round and sweet. We love it!\n\n Big Coconut is fun. \"Coconut, Coconut,\" has sweet water. Drink it up!\n\n Red Pomegranate has many seeds. \"Pomegranate, Pomegranate,\" bright and tasty. Pop, pop, pop!\n\n Blue Blueberries are tiny. \"Blueberry, Blueberry,\" blue and sweet. So cute!\n\n Red Raspberry is soft. \"Raspberry, Raspberry,\" with little bumps. Yum!\n\n Black Blackberry is here. \"Blackberry, Blackberry,\" dark and sweet. Nice to eat!\n\n Red Cranberry is tart. \"Cranberry, Cranberry,\" small and red. Good for you!\n\n Purple Plum is juicy. \"Plum, Plum,\" round and sweet. We all smile!\n\n Wow, what a fun fruit party! We know Apple, Orange, Banana and more. All fruits are yummy. We love fruits!",
    keyWords: ["Apple", "Orange", "Banana", "Grape", "Strawberry", "Watermelon", "Peach", "Pear", "Pineapple", "Kiwi", "Mango", "Lychee", "Longan", "Coconut", "Pomegranate", "Blueberry", "Raspberry", "Blackberry", "Cranberry", "Plum", "fruit"]
  },
  {
    id: 4,
    title: "Xiao Ming's Happy Day",
    category: "日常",
    titleChinese: "小明的快乐一天",
    content: "Good morning! Xiao Ming wakes up in his small House (房子). Next to his bed, there is an Alarm Clock (闹钟) that woke him up. He puts on his Clothes (衣服), Socks (袜子), and Shoes (鞋子). Then he goes to the bathroom. He uses a Toothbrush (牙刷) and Toothpaste (牙膏) to brush his teeth. After that, he washes his hands with Soap (肥皂) and dries them with a soft Towel (毛巾). He looks at himself in the Mirror (镜子) and smiles!\n\nThen it's breakfast time. Mom puts porridge in a Bowl (碗) and eggs on a Plate (盘子). Xiao Ming uses a Spoon (勺子) and a Fork (叉子) to eat. He drinks milk from a red Cup (杯子). After breakfast, Mom gives him a small Gift (礼物) – it's a new Comb (梳子)!\n\nNow it's time to go to School (学校). Xiao Ming takes his School Bag (书包). Inside the bag, there is a Pencil Case (铅笔盒). In the pencil case, there are many things: a Pencil (铅笔), a Pen (钢笔), an Eraser (橡皮擦), a Ruler (尺子), and a colorful Crayon (蜡笔) and Marker (水彩笔). He also puts his new Notebook (笔记本), a Dictionary (字典), a Map (地图), and a small Globe (地球仪) in his bag. He wears his Hat (帽子) because it's sunny outside.\n\nAt school, Xiao Ming meets his kind Teacher (老师). They read a fun Book (书) together. During art class, they draw a big Tree (树) with pink Flower (花) on paper. Xiao Ming uses his Crayon (蜡笔) and Marker (水彩笔) to make the picture beautiful.\n\nAfter school, it starts to rain. Lucky for Xiao Ming, he has a blue Umbrella (雨伞) in his bag! When he gets home, he uses the Key (钥匙) to open the door. Mom is in the kitchen. She is cooking soup in a big Pot (锅) and frying vegetables in a Pan (平底锅) with a Spatula (铲子). There is food in the Fridge (冰箱) and clean clothes in the Washing Machine (洗衣机). For dinner, they use Chopsticks (筷子) to eat delicious rice.\n\nIn the evening, Xiao Ming watches his favorite cartoon on TV (电视) for a little while. Then he uses the Computer (电脑) to play a fun English game. Before bed, he checks the time on his small Watch (手表). Mom calls him with her Phone (手机) to come to bed.\n\nIt's a cold night, so Xiao Ming puts on his warm Gloves (手套) and wraps a soft Scarf (围巾) around his neck when he goes to the living room to say goodnight. What a happy day Xiao Ming has! He knows so many nice things around him, and he loves them all.",
    keyWords: ["House", "Alarm Clock", "Clothes", "Socks", "Shoes", "Toothbrush", "Toothpaste", "Soap", "Towel", "Mirror", "Bowl", "Plate", "Spoon", "Fork", "Cup", "Gift", "Comb", "School", "School Bag", "Pencil Case", "Pencil", "Pen", "Eraser", "Ruler", "Crayon", "Marker", "Notebook", "Dictionary", "Map", "Globe", "Hat", "Teacher", "Book", "Tree", "Flower", "Umbrella", "Key", "Pot", "Pan", "Spatula", "Fridge", "Washing Machine", "Chopsticks", "TV", "Computer", "Watch", "Phone", "Gloves", "Scarf"]
  }
];

// 获取指定类别的文章
function getReadingArticles(category = "all") {
  if (category === "all") {
    return window.readingArticles;
  }
  return window.readingArticles.filter(article => article.category === category);
}

// 根据ID获取文章
function getArticleById(id) {
  return window.readingArticles.find(article => article.id === id);
}