// 英语单词词汇表
const vocabularyList = [
  // 动物类
  { chinese: "企鹅", english: "Penguin", phonetic: "/ˈpeŋ.ɡwɪn/", category: "animal" },
  { chinese: "狮子", english: "Lion", phonetic: "/ˈlaɪ.ən/", category: "animal" },
  { chinese: "鲸鱼", english: "Whale", phonetic: "/weɪl/", category: "animal" },
  { chinese: "猴子", english: "Monkey", phonetic: "/ˈmʌŋ.ki/", category: "animal" },
  { chinese: "兔子", english: "Rabbit", phonetic: "/ˈræb.ɪt/", category: "animal" },
  { chinese: "狐狸", english: "Fox", phonetic: "/fɒks/", category: "animal" },
  { chinese: "斑马", english: "Zebra", phonetic: "/ˈzeb.rə/", category: "animal" },
  { chinese: "大象", english: "Elephant", phonetic: "/ˈel.ɪ.fənt/", category: "animal" },
  { chinese: "鸟", english: "Bird", phonetic: "/bɜːd/", category: "animal" },
  { chinese: "鱼", english: "Fish", phonetic: "/fɪʃ/", category: "animal" },
  { chinese: "青蛙", english: "Frog", phonetic: "/frɒɡ/", category: "animal" },
  { chinese: "蝴蝶", english: "Butterfly", phonetic: "/ˈbʌtəflaɪ/", category: "animal" },
  { chinese: "蜜蜂", english: "Bee", phonetic: "/biː/", category: "animal" },
  { chinese: "蚂蚁", english: "Ant", phonetic: "/ænt/", category: "animal" },
  { chinese: "蜗牛", english: "Snail", phonetic: "/sneɪl/", category: "animal" },
  { chinese: "乌龟", english: "Turtle", phonetic: "/ˈtɜːtl/", category: "animal" },
  { chinese: "仓鼠", english: "Hamster", phonetic: "/ˈhæmstər/", category: "animal" },
  { chinese: "豚鼠", english: "Guinea Pig", phonetic: "/ˈɡɪni pɪɡ/", category: "animal" },
  { chinese: "老鼠", english: "Mouse", phonetic: "/maʊs/", category: "animal" },
  { chinese: "奶牛", english: "Cow", phonetic: "/kaʊ/", category: "animal" },
  { chinese: "马", english: "Horse", phonetic: "/hɔːs/", category: "animal" },
  { chinese: "羊", english: "Sheep", phonetic: "/ʃiːp/", category: "animal" },
  { chinese: "猪", english: "Pig", phonetic: "/pɪɡ/", category: "animal" },
  { chinese: "鸡", english: "Chicken", phonetic: "/ˈtʃɪkɪn/", category: "animal" },
  { chinese: "鸭", english: "Duck", phonetic: "/dʌk/", category: "animal" },
  { chinese: "鹅", english: "Goose", phonetic: "/ɡuːs/", category: "animal" },
  { chinese: "鸽子", english: "Pigeon", phonetic: "/ˈpɪdʒɪn/", category: "animal" },
  { chinese: "猫", english: "Cat", phonetic: "/kæt/", category: "animal" },
  { chinese: "狗", english: "Dog", phonetic: "/dɒɡ/", category: "animal" },
  { chinese: "长颈鹿", english: "Giraffe", phonetic: "/dʒəˈrɑːf/", category: "animal" },
  { chinese: "熊猫", english: "Panda", phonetic: "/ˈpændə/", category: "animal" },
  { chinese: "老虎", english: "Tiger", phonetic: "/ˈtaɪɡə/", category: "animal" },
  { chinese: "熊", english: "Bear", phonetic: "/beə/", category: "animal" },
  { chinese: "狼", english: "Wolf", phonetic: "/wʊlf/", category: "animal" },
  { chinese: "河马", english: "Hippo", phonetic: "/ˈhɪpəʊ/", category: "animal" },
  { chinese: "鳄鱼", english: "Crocodile", phonetic: "/ˈkrɒkədaɪl/", category: "animal" },
  { chinese: "蜥蜴", english: "Lizard", phonetic: "/ˈlɪzəd/", category: "animal" },
  { chinese: "蛇", english: "Snake", phonetic: "/sneɪk/", category: "animal" },
  { chinese: "蜘蛛", english: "Spider", phonetic: "/ˈspaɪdə/", category: "animal" },
  { chinese: "瓢虫", english: "Ladybug", phonetic: "/ˈleɪdibʌɡ/", category: "animal" },
  { chinese: "蜻蜓", english: "Dragonfly", phonetic: "/ˈdræɡənflaɪ/", category: "animal" },
  { chinese: "苍蝇", english: "Fly", phonetic: "/flaɪ/", category: "animal" },
  { chinese: "蚊子", english: "Mosquito", phonetic: "/məˈskiːtəʊ/", category: "animal" },
  { chinese: "蟑螂", english: "Cockroach", phonetic: "/ˈkɒkrəʊtʃ/", category: "animal" },
  { chinese: "小鸟", english: "Birdie", phonetic: "/ˈbɜːdi/", category: "animal" },
  { chinese: "金鱼", english: "Goldfish", phonetic: "/ˈɡəʊldfɪʃ/", category: "animal" },
  { chinese: "蝌蚪", english: "Tadpole", phonetic: "/ˈtædpəʊl/", category: "animal" },
  { chinese: "毛毛虫", english: "Caterpillar", phonetic: "/ˈkætəpɪlə/", category: "animal" },

  // 食物类
  { chinese: "蔬菜", english: "Vegetable", phonetic: "/ˈvedʒ.tə.bəl/", category: "food" },
  { chinese: "冰淇淋", english: "Ice Cream", phonetic: "/ˌaɪs ˈkriːm/", category: "food" },
  { chinese: "面条", english: "Noodle", phonetic: "/ˈnuː.dl/", category: "food" },
  { chinese: "果汁", english: "Juice", phonetic: "/dʒuːs/", category: "food" },
  { chinese: "面包", english: "Bread", phonetic: "/bred/", category: "food" },
  { chinese: "牛奶", english: "Milk", phonetic: "/mɪlk/", category: "food" },
  { chinese: "鸡蛋", english: "Egg", phonetic: "/eɡ/", category: "food" },
  { chinese: "米饭", english: "Rice", phonetic: "/raɪs/", category: "food" },
  { chinese: "蛋糕", english: "Cake", phonetic: "/keɪk/", category: "food" },
  { chinese: "饼干", english: "Cookie", phonetic: "/ˈkʊki/", category: "food" },
  { chinese: "糖果", english: "Candy", phonetic: "/ˈkændi/", category: "food" },
  { chinese: "巧克力", english: "Chocolate", phonetic: "/ˈtʃɒklət/", category: "food" },
  { chinese: "奶酪", english: "Cheese", phonetic: "/tʃiːz/", category: "food" },
  { chinese: "水果", english: "Fruit", phonetic: "/fruːt/", category: "food" },
  { chinese: "肉", english: "Meat", phonetic: "/miːt/", category: "food" },
  { chinese: "汉堡", english: "Hamburger", phonetic: "/ˈhæmbɜːɡə/", category: "food" },
  { chinese: "披萨", english: "Pizza", phonetic: "/ˈpiːtsə/", category: "food" },
  { chinese: "水", english: "Water", phonetic: "/ˈwɔːtə/", category: "food" },
  { chinese: "茶", english: "Tea", phonetic: "/tiː/", category: "food" },
  { chinese: "热狗", english: "Hot Dog", phonetic: "/hɒt dɒɡ/", category: "food" },
  { chinese: "三明治", english: "Sandwich", phonetic: "/ˈsænwɪtʃ/", category: "food" },
  { chinese: "薯条", english: "French Fries", phonetic: "/frentʃ fraɪz/", category: "food" },
  { chinese: "炸鸡", english: "Fried Chicken", phonetic: "/fraɪd ˈtʃɪkɪn/", category: "food" },
  { chinese: "沙拉", english: "Salad", phonetic: "/ˈsæləd/", category: "food" },
  { chinese: "汤", english: "Soup", phonetic: "/suːp/", category: "food" },
  { chinese: "牛排", english: "Steak", phonetic: "/steɪk/", category: "food" },
  { chinese: "牛肉", english: "Beef", phonetic: "/biːf/", category: "food" },
  { chinese: "猪肉", english: "Pork", phonetic: "/pɔːk/", category: "food" },
  { chinese: "酸奶", english: "Yogurt", phonetic: "/ˈjɒɡət/", category: "food" },
  { chinese: "可乐", english: "Coke", phonetic: "/kəʊk/", category: "food" },
  { chinese: "雪碧", english: "Sprite", phonetic: "/spraɪt/", category: "food" },
  { chinese: "咖啡", english: "Coffee", phonetic: "/ˈkɒfi/", category: "food" },
  { chinese: "奶茶", english: "Milk Tea", phonetic: "/mɪlk tiː/", category: "food" },

  // 水果类
  { chinese: "苹果", english: "Apple", phonetic: "/ˈæp.əl/", category: "fruit" },
  { chinese: "橘子", english: "Orange", phonetic: "/ˈɒr.ɪndʒ/", category: "fruit" },
  { chinese: "香蕉", english: "Banana", phonetic: "/bəˈnɑː.nə/", category: "fruit" },
  { chinese: "葡萄", english: "Grape", phonetic: "/ɡreɪp/", category: "fruit" },
  { chinese: "草莓", english: "Strawberry", phonetic: "/ˈstrɔːbəri/", category: "fruit" },
  { chinese: "西瓜", english: "Watermelon", phonetic: "/ˈwɔːtəmelən/", category: "fruit" },
  { chinese: "桃子", english: "Peach", phonetic: "/piːtʃ/", category: "fruit" },
  { chinese: "梨", english: "Pear", phonetic: "/peə/", category: "fruit" },
  { chinese: "菠萝", english: "Pineapple", phonetic: "/ˈpaɪnæpl/", category: "fruit" },
  { chinese: "猕猴桃", english: "Kiwi", phonetic: "/ˈkiːwi/", category: "fruit" },
  { chinese: "芒果", english: "Mango", phonetic: "/ˈmæŋɡəʊ/", category: "fruit" },
  { chinese: "荔枝", english: "Lychee", phonetic: "/ˈlaɪtʃiː/", category: "fruit" },
  { chinese: "龙眼", english: "Longan", phonetic: "/ˈlɒŋɡən/", category: "fruit" },
  { chinese: "椰子", english: "Coconut", phonetic: "/ˈkəʊkənʌt/", category: "fruit" },
  { chinese: "石榴", english: "Pomegranate", phonetic: "/ˈpɒmɪɡrænɪt/", category: "fruit" },
  { chinese: "蓝莓", english: "Blueberry", phonetic: "/ˈbluːbəri/", category: "fruit" },
  { chinese: "覆盆子", english: "Raspberry", phonetic: "/ˈrɑːzbəri/", category: "fruit" },
  { chinese: "黑莓", english: "Blackberry", phonetic: "/ˈblækbəri/", category: "fruit" },
  { chinese: "蔓越莓", english: "Cranberry", phonetic: "/ˈkrænbəri/", category: "fruit" },
  { chinese: "李子", english: "Plum", phonetic: "/plʌm/", category: "fruit" },

  // 日常用品类
  { chinese: "钥匙", english: "Key", phonetic: "/kiː/", category: "daily" },
  { chinese: "雨伞", english: "Umbrella", phonetic: "/ʌmˈbrel.ə/", category: "daily" },
  { chinese: "铅笔", english: "Pencil", phonetic: "/ˈpen.səl/", category: "daily" },
  { chinese: "礼物", english: "Gift", phonetic: "/ɡɪft/", category: "daily" },
  { chinese: "杯子", english: "Cup", phonetic: "/kʌp/", category: "daily" },
  { chinese: "碗", english: "Bowl", phonetic: "/bəʊl/", category: "daily" },
  { chinese: "盘子", english: "Plate", phonetic: "/pleɪt/", category: "daily" },
  { chinese: "勺子", english: "Spoon", phonetic: "/spuːn/", category: "daily" },
  { chinese: "叉子", english: "Fork", phonetic: "/fɔːk/", category: "daily" },
  { chinese: "刀子", english: "Knife", phonetic: "/naɪf/", category: "daily" },
  { chinese: "毛巾", english: "Towel", phonetic: "/ˈtaʊəl/", category: "daily" },
  { chinese: "牙刷", english: "Toothbrush", phonetic: "/ˈtuːθbrʌʃ/", category: "daily" },
  { chinese: "牙膏", english: "Toothpaste", phonetic: "/ˈtuːθpeɪst/", category: "daily" },
  { chinese: "肥皂", english: "Soap", phonetic: "/səʊp/", category: "daily" },
  { chinese: "洗发水", english: "Shampoo", phonetic: "/ʃæmˈpuː/", category: "daily" },
  { chinese: "梳子", english: "Comb", phonetic: "/kəʊm/", category: "daily" },
  { chinese: "镜子", english: "Mirror", phonetic: "/ˈmɪrə/", category: "daily" },
  { chinese: "衣服", english: "Clothes", phonetic: "/kləʊðz/", category: "daily" },
  { chinese: "鞋子", english: "Shoes", phonetic: "/ʃuːz/", category: "daily" },
  { chinese: "帽子", english: "Hat", phonetic: "/hæt/", category: "daily" },
  { chinese: "袜子", english: "Socks", phonetic: "/sɒks/", category: "daily" },
  { chinese: "手套", english: "Gloves", phonetic: "/ɡlʌvz/", category: "daily" },
  { chinese: "围巾", english: "Scarf", phonetic: "/skɑːf/", category: "daily" },
  { chinese: "花", english: "Flower", phonetic: "/ˈflaʊ.ər/", category: "daily" },
  { chinese: "房子", english: "House", phonetic: "/haʊs/", category: "daily" },
  { chinese: "树", english: "Tree", phonetic: "/triː/", category: "daily" },
  { chinese: "书", english: "Book", phonetic: "/bʊk/", category: "daily" },
  { chinese: "学校", english: "School", phonetic: "/skuːl/", category: "daily" },
  { chinese: "老师", english: "Teacher", phonetic: "/ˈtiː.tʃər/", category: "daily" },
  { chinese: "书包", english: "School Bag", phonetic: "/skuːl bæɡ/", category: "daily" },
  { chinese: "铅笔盒", english: "Pencil Case", phonetic: "/ˈpensl keɪs/", category: "daily" },
  { chinese: "橡皮擦", english: "Eraser", phonetic: "/ɪˈreɪzə/", category: "daily" },
  { chinese: "尺子", english: "Ruler", phonetic: "/ˈruːlə/", category: "daily" },
  { chinese: "钢笔", english: "Pen", phonetic: "/pen/", category: "daily" },
  { chinese: "笔记本", english: "Notebook", phonetic: "/ˈnəʊtbʊk/", category: "daily" },
  { chinese: "字典", english: "Dictionary", phonetic: "/ˈdɪkʃənri/", category: "daily" },
  { chinese: "地图", english: "Map", phonetic: "/mæp/", category: "daily" },
  { chinese: "地球仪", english: "Globe", phonetic: "/ɡləʊb/", category: "daily" },
  { chinese: "闹钟", english: "Alarm Clock", phonetic: "/əˈlɑːm klɒk/", category: "daily" },
  { chinese: "手表", english: "Watch", phonetic: "/wɒtʃ/", category: "daily" },
  { chinese: "手机", english: "Phone", phonetic: "/fəʊn/", category: "daily" },
  { chinese: "电脑", english: "Computer", phonetic: "/kəmˈpjuːtə/", category: "daily" },
  { chinese: "电视", english: "TV", phonetic: "/ˌtiː ˈviː/", category: "daily" },
  { chinese: "冰箱", english: "Fridge", phonetic: "/frɪdʒ/", category: "daily" },
  { chinese: "洗衣机", english: "Washing Machine", phonetic: "/ˈwɒʃɪŋ məˈʃiːn/", category: "daily" },
  { chinese: "微波炉", english: "Microwave", phonetic: "/ˈmaɪkrəweɪv/", category: "daily" },
  { chinese: "烤箱", english: "Oven", phonetic: "/ˈʌvn/", category: "daily" },
  { chinese: "炉灶", english: "Stove", phonetic: "/stəʊv/", category: "daily" },
  { chinese: "锅", english: "Pot", phonetic: "/pɒt/", category: "daily" },
  { chinese: "平底锅", english: "Pan", phonetic: "/pæn/", category: "daily" },
  { chinese: "铲子", english: "Spatula", phonetic: "/ˈspætʃələ/", category: "daily" },
  { chinese: "筷子", english: "Chopsticks", phonetic: "/ˈtʃɒpstɪks/", category: "daily" },
  { chinese: "蜡笔", english: "Crayon", phonetic: "/ˈkreɪən/", category: "daily" },
  { chinese: "水彩笔", english: "Marker", phonetic: "/ˈmɑːkə/", category: "daily" },

  // 颜色类
  { chinese: "红色", english: "Red", phonetic: "/red/", category: "color" },
  { chinese: "蓝色", english: "Blue", phonetic: "/bluː/", category: "color" },
  { chinese: "黄色", english: "Yellow", phonetic: "/ˈjeləʊ/", category: "color" },
  { chinese: "绿色", english: "Green", phonetic: "/ɡriːn/", category: "color" },
  { chinese: "紫色", english: "Purple", phonetic: "/ˈpɜːpl/", category: "color" },
  { chinese: "橙色", english: "Orange", phonetic: "/ˈɒrɪndʒ/", category: "color" },
  { chinese: "粉色", english: "Pink", phonetic: "/pɪŋk/", category: "color" },
  { chinese: "黑色", english: "Black", phonetic: "/blæk/", category: "color" },
  { chinese: "白色", english: "White", phonetic: "/waɪt/", category: "color" },
  { chinese: "灰色", english: "Gray", phonetic: "/ɡreɪ/", category: "color" },
  { chinese: "棕色", english: "Brown", phonetic: "/braʊn/", category: "color" },
  { chinese: "金色", english: "Gold", phonetic: "/ɡəʊld/", category: "color" },
  { chinese: "银色", english: "Silver", phonetic: "/ˈsɪlvə/", category: "color" },

  // 数字类
  { chinese: "一", english: "One", phonetic: "/wʌn/", category: "number" },
  { chinese: "二", english: "Two", phonetic: "/tuː/", category: "number" },
  { chinese: "三", english: "Three", phonetic: "/θriː/", category: "number" },
  { chinese: "四", english: "Four", phonetic: "/fɔː/", category: "number" },
  { chinese: "五", english: "Five", phonetic: "/faɪv/", category: "number" },
  { chinese: "六", english: "Six", phonetic: "/sɪks/", category: "number" },
  { chinese: "七", english: "Seven", phonetic: "/ˈsevn/", category: "number" },
  { chinese: "八", english: "Eight", phonetic: "/eɪt/", category: "number" },
  { chinese: "九", english: "Nine", phonetic: "/naɪn/", category: "number" },
  { chinese: "十", english: "Ten", phonetic: "/ten/", category: "number" },
  { chinese: "十一", english: "Eleven", phonetic: "/ɪˈlevn/", category: "number" },
  { chinese: "十二", english: "Twelve", phonetic: "/twelv/", category: "number" },
  { chinese: "十三", english: "Thirteen", phonetic: "/ˌθɜːˈtiːn/", category: "number" },
  { chinese: "十四", english: "Fourteen", phonetic: "/ˌfɔːˈtiːn/", category: "number" },
  { chinese: "十五", english: "Fifteen", phonetic: "/ˌfɪfˈtiːn/", category: "number" },
  { chinese: "十六", english: "Sixteen", phonetic: "/ˌsɪksˈtiːn/", category: "number" },
  { chinese: "十七", english: "Seventeen", phonetic: "/ˌsevənˈtiːn/", category: "number" },
  { chinese: "十八", english: "Eighteen", phonetic: "/ˌeɪˈtiːn/", category: "number" },
  { chinese: "十九", english: "Nineteen", phonetic: "/ˌnaɪnˈtiːn/", category: "number" },
  { chinese: "二十", english: "Twenty", phonetic: "/ˈtwenti/", category: "number" },
  { chinese: "三十", english: "Thirty", phonetic: "/ˈθɜːti/", category: "number" },
  { chinese: "四十", english: "Forty", phonetic: "/ˈfɔːti/", category: "number" },
  { chinese: "五十", english: "Fifty", phonetic: "/ˈfɪfti/", category: "number" },
  { chinese: "六十", english: "Sixty", phonetic: "/ˈsɪksti/", category: "number" },
  { chinese: "七十", english: "Seventy", phonetic: "/ˈsevnti/", category: "number" },
  { chinese: "八十", english: "Eighty", phonetic: "/ˈeɪti/", category: "number" },
  { chinese: "九十", english: "Ninety", phonetic: "/ˈnaɪnti/", category: "number" },
  { chinese: "一百", english: "One Hundred", phonetic: "/wʌn ˈhʌndrəd/", category: "number" },

  // 交通工具类
  { chinese: "汽车", english: "Car", phonetic: "/kɑː/", category: "transport" },
  { chinese: "公交车", english: "Bus", phonetic: "/bʌs/", category: "transport" },
  { chinese: "出租车", english: "Taxi", phonetic: "/ˈtæksi/", category: "transport" },
  { chinese: "自行车", english: "Bicycle", phonetic: "/ˈbaɪsɪkl/", category: "transport" },
  { chinese: "摩托车", english: "Motorcycle", phonetic: "/ˈməʊtəsaɪkl/", category: "transport" },
  { chinese: "火车", english: "Train", phonetic: "/treɪn/", category: "transport" },
  { chinese: "飞机", english: "Airplane", phonetic: "/ˈeəpleɪn/", category: "transport" },
  { chinese: "船", english: "Ship", phonetic: "/ʃɪp/", category: "transport" },
  { chinese: "小船", english: "Boat", phonetic: "/bəʊt/", category: "transport" },
  { chinese: "直升机", english: "Helicopter", phonetic: "/ˈhelɪkɒptə/", category: "transport" },
  { chinese: "地铁", english: "Subway", phonetic: "/ˈsʌbweɪ/", category: "transport" },
  { chinese: "高铁", english: "High-speed Train", phonetic: "/haɪ spiːd treɪn/", category: "transport" },
  { chinese: "货车", english: "Truck", phonetic: "/trʌk/", category: "transport" },
  { chinese: "救护车", english: "Ambulance", phonetic: "/ˈæmbjələns/", category: "transport" },
  { chinese: "消防车", english: "Fire Truck", phonetic: "/faɪə trʌk/", category: "transport" },
  { chinese: "警车", english: "Police Car", phonetic: "/pəˈliːs kɑː/", category: "transport" },
  { chinese: "救火车", english: "Fire Engine", phonetic: "/faɪə ˈendʒɪn/", category: "transport" },
  { chinese: "双层巴士", english: "Double-decker Bus", phonetic: "/ˌdʌbl ˈdekə bʌs/", category: "transport" },
  { chinese: "缆车", english: "Cable Car", phonetic: "/ˈkeɪbl kɑː/", category: "transport" },
  { chinese: "热气球", english: "Hot Air Balloon", phonetic: "/hɒt eə bəˈluːn/", category: "transport" },

  // 身体部位类
  { chinese: "头", english: "Head", phonetic: "/hed/", category: "body" },
  { chinese: "眼睛", english: "Eye", phonetic: "/aɪ/", category: "body" },
  { chinese: "鼻子", english: "Nose", phonetic: "/nəʊz/", category: "body" },
  { chinese: "嘴", english: "Mouth", phonetic: "/maʊθ/", category: "body" },
  { chinese: "耳朵", english: "Ear", phonetic: "/ɪə/", category: "body" },
  { chinese: "脸", english: "Face", phonetic: "/feɪs/", category: "body" },
  { chinese: "手", english: "Hand", phonetic: "/hænd/", category: "body" },
  { chinese: "手指", english: "Finger", phonetic: "/ˈfɪŋɡə/", category: "body" },
  { chinese: "脚", english: "Foot", phonetic: "/fʊt/", category: "body" },
  { chinese: "腿", english: "Leg", phonetic: "/leɡ/", category: "body" },
  { chinese: "胳膊", english: "Arm", phonetic: "/ɑːm/", category: "body" },
  { chinese: "肩膀", english: "Shoulder", phonetic: "/ˈʃəʊldə/", category: "body" },
  { chinese: "膝盖", english: "Knee", phonetic: "/niː/", category: "body" },
  { chinese: "脚趾", english: "Toe", phonetic: "/təʊ/", category: "body" },
  { chinese: "头发", english: "Hair", phonetic: "/heə/", category: "body" },
  { chinese: "牙齿", english: "Tooth", phonetic: "/tuːθ/", category: "body" },
  { chinese: "舌头", english: "Tongue", phonetic: "/tʌŋ/", category: "body" },
  { chinese: "喉咙", english: "Throat", phonetic: "/θrəʊt/", category: "body" },
  { chinese: "脖子", english: "Neck", phonetic: "/nek/", category: "body" },
  { chinese: "背部", english: "Back", phonetic: "/bæk/", category: "body" },
  { chinese: "胸部", english: "Chest", phonetic: "/tʃest/", category: "body" },
  { chinese: "腹部", english: "Stomach", phonetic: "/ˈstʌmək/", category: "body" },
  { chinese: "臀部", english: "Bottom", phonetic: "/ˈbɒtəm/", category: "body" },
  { chinese: "皮肤", english: "Skin", phonetic: "/skɪn/", category: "body" },
  { chinese: "骨头", english: "Bone", phonetic: "/bəʊn/", category: "body" },
  { chinese: "肌肉", english: "Muscle", phonetic: "/ˈmʌsl/", category: "body" },
  { chinese: "心脏", english: "Heart", phonetic: "/hɑːt/", category: "body" },
  { chinese: "肝脏", english: "Liver", phonetic: "/ˈlɪvə/", category: "body" },
  { chinese: "肺", english: "Lung", phonetic: "/lʌŋ/", category: "body" },

  // 亲属类
  { chinese: "爸爸", english: "Father", phonetic: "/ˈfɑːðər/", category: "family" },
  { chinese: "妈妈", english: "Mother", phonetic: "/ˈmʌðər/", category: "family" },
  { chinese: "兄弟", english: "Brother", phonetic: "/ˈbrʌðər/", category: "family" },
  { chinese: "姐妹", english: "Sister", phonetic: "/ˈsɪstər/", category: "family" },
  { chinese: "祖父", english: "Grandfather", phonetic: "/ˈɡrænfɑːðər/", category: "family" },
  { chinese: "祖母", english: "Grandmother", phonetic: "/ˈɡrænmʌðər/", category: "family" },
  { chinese: "儿子", english: "Son", phonetic: "/sʌn/", category: "family" },
  { chinese: "女儿", english: "Daughter", phonetic: "/ˈdɔːtər/", category: "family" },
  { chinese: "叔叔", english: "Uncle", phonetic: "/ˈʌŋkl/", category: "family" },
  { chinese: "阿姨", english: "Aunt", phonetic: "/ænt/", category: "family" },
  { chinese: "堂兄弟", english: "Cousin", phonetic: "/ˈkʌzn/", category: "family" },
  { chinese: "丈夫", english: "Husband", phonetic: "/ˈhʌzbənd/", category: "family" },
  { chinese: "妻子", english: "Wife", phonetic: "/waɪf/", category: "family" },
  { chinese: "爷爷", english: "Grandpa", phonetic: "/ˈɡrænpɑː/", category: "family" },
  { chinese: "奶奶", english: "Grandma", phonetic: "/ˈɡrænmɑː/", category: "family" },
  { chinese: "外公", english: "Maternal Grandpa", phonetic: "/məˈtɜːnl ˈɡrænpɑː/", category: "family" },
  { chinese: "外婆", english: "Maternal Grandma", phonetic: "/məˈtɜːnl ˈɡrænmɑː/", category: "family" },
  { chinese: "侄子", english: "Nephew", phonetic: "/ˈnefjuː/", category: "family" },
  { chinese: "侄女", english: "Niece", phonetic: "/niːs/", category: "family" },
  { chinese: "孙子", english: "Grandson", phonetic: "/ˈɡrænsʌn/", category: "family" },
  { chinese: "孙女", english: "Granddaughter", phonetic: "/ˈɡrændɔːtə/", category: "family" },
  { chinese: "姐夫", english: "Brother-in-law", phonetic: "/ˌbrʌðə ɪn ˈlɔː/", category: "family" },
  { chinese: "嫂子", english: "Sister-in-law", phonetic: "/ˌsɪstə ɪn ˈlɔː/", category: "family" },
  { chinese: "妹夫", english: "Brother-in-law", phonetic: "/ˌbrʌðə ɪn ˈlɔː/", category: "family" },
  { chinese: "弟媳", english: "Sister-in-law", phonetic: "/ˌsɪstə ɪn ˈlɔː/", category: "family" },
  { chinese: "婆婆", english: "Mother-in-law", phonetic: "/ˌmʌðə ɪn ˈlɔː/", category: "family" },
  { chinese: "公公", english: "Father-in-law", phonetic: "/ˌfɑːðə ɪn ˈlɔː/", category: "family" },
  { chinese: "岳母", english: "Mother-in-law", phonetic: "/ˌmʌðə ɪn ˈlɔː/", category: "family" },
  { chinese: "岳父", english: "Father-in-law", phonetic: "/ˌfɑːðə ɪn ˈlɔː/", category: "family" },
  { chinese: "全家", english: "Family", phonetic: "/ˈfæməli/", category: "family" },

  // 天气类
  { chinese: "太阳", english: "Sun", phonetic: "/sʌn/", category: "weather" },
  { chinese: "月亮", english: "Moon", phonetic: "/muːn/", category: "weather" },
  { chinese: "星星", english: "Star", phonetic: "/stɑː/", category: "weather" },
  { chinese: "云", english: "Cloud", phonetic: "/klaʊd/", category: "weather" },
  { chinese: "雨", english: "Rain", phonetic: "/reɪn/", category: "weather" },
  { chinese: "雪", english: "Snow", phonetic: "/snəʊ/", category: "weather" },
  { chinese: "风", english: "Wind", phonetic: "/wɪnd/", category: "weather" },
  { chinese: "雾", english: "Fog", phonetic: "/fɒɡ/", category: "weather" },
  { chinese: "雷", english: "Thunder", phonetic: "/ˈθʌndə/", category: "weather" },
  { chinese: "闪电", english: "Lightning", phonetic: "/ˈlaɪtnɪŋ/", category: "weather" },
  { chinese: "雷阵雨", english: "Thunderstorm", phonetic: "/ˈθʌndəstɔːm/", category: "weather" },
  { chinese: "彩虹", english: "Rainbow", phonetic: "/ˈreɪnbəʊ/", category: "weather" },
  { chinese: "温度", english: "Temperature", phonetic: "/ˈtemprətʃə/", category: "weather" },
  { chinese: "热", english: "Hot", phonetic: "/hɒt/", category: "weather" },
  { chinese: "冷", english: "Cold", phonetic: "/kəʊld/", category: "weather" },
  { chinese: "暖和", english: "Warm", phonetic: "/wɔːm/", category: "weather" },
  { chinese: "凉爽", english: "Cool", phonetic: "/kuːl/", category: "weather" },
  { chinese: "天气", english: "Weather", phonetic: "/ˈweðə/", category: "weather" },

  // 动作类
  { chinese: "跑", english: "Run", phonetic: "/rʌn/", category: "action" },
  { chinese: "走", english: "Walk", phonetic: "/wɔːk/", category: "action" },
  { chinese: "跳", english: "Jump", phonetic: "/dʒʌmp/", category: "action" },
  { chinese: "爬", english: "Climb", phonetic: "/klaɪm/", category: "action" },
  { chinese: "吃", english: "Eat", phonetic: "/iːt/", category: "action" },
  { chinese: "喝", english: "Drink", phonetic: "/drɪŋk/", category: "action" },
  { chinese: "睡", english: "Sleep", phonetic: "/sliːp/", category: "action" },
  { chinese: "玩", english: "Play", phonetic: "/pleɪ/", category: "action" },
  { chinese: "笑", english: "Smile", phonetic: "/smaɪl/", category: "action" },
  { chinese: "哭", english: "Cry", phonetic: "/kraɪ/", category: "action" },
  { chinese: "唱", english: "Sing", phonetic: "/sɪŋ/", category: "action" },
  { chinese: "跳", english: "Dance", phonetic: "/dɑːns/", category: "action" },
  { chinese: "画", english: "Draw", phonetic: "/drɔː/", category: "action" },
  { chinese: "写", english: "Write", phonetic: "/raɪt/", category: "action" },
  { chinese: "读", english: "Read", phonetic: "/riːd/", category: "action" },
  { chinese: "听", english: "Listen", phonetic: "/ˈlɪsn/", category: "action" },
  { chinese: "看", english: "Look", phonetic: "/lʊk/", category: "action" },
  { chinese: "说", english: "Speak", phonetic: "/spiːk/", category: "action" },
  { chinese: "喊", english: "Shout", phonetic: "/ʃaʊt/", category: "action" },
  { chinese: "叫", english: "Call", phonetic: "/kɔːl/", category: "action" },
  { chinese: "抱", english: "Hug", phonetic: "/hʌɡ/", category: "action" },
  { chinese: "吻", english: "Kiss", phonetic: "/kɪs/", category: "action" },
  { chinese: "推", english: "Push", phonetic: "/pʊʃ/", category: "action" },
  { chinese: "拉", english: "Pull", phonetic: "/pʊl/", category: "action" },
  { chinese: "举", english: "Lift", phonetic: "/lɪft/", category: "action" },
  { chinese: "放", english: "Put", phonetic: "/pʊt/", category: "action" },
  { chinese: "给", english: "Give", phonetic: "/ɡɪv/", category: "action" },
  { chinese: "拿", english: "Take", phonetic: "/teɪk/", category: "action" },
  { chinese: "扔", english: "Throw", phonetic: "/θrəʊ/", category: "action" },
  { chinese: "接", english: "Catch", phonetic: "/kætʃ/", category: "action" },

  // 情感类
  { chinese: "开心", english: "Happy", phonetic: "/ˈhæpi/", category: "emotion" },
  { chinese: "伤心", english: "Sad", phonetic: "/sæd/", category: "emotion" },
  { chinese: "生气", english: "Angry", phonetic: "/ˈæŋɡri/", category: "emotion" },
  { chinese: "害怕", english: "Afraid", phonetic: "/əˈfreɪd/", category: "emotion" },
  { chinese: "惊讶", english: "Surprised", phonetic: "/səˈpraɪzd/", category: "emotion" },
  { chinese: "爱", english: "Love", phonetic: "/lʌv/", category: "emotion" },
  { chinese: "喜欢", english: "Like", phonetic: "/laɪk/", category: "emotion" },
  { chinese: "讨厌", english: "Hate", phonetic: "/heɪt/", category: "emotion" },
  { chinese: "兴奋", english: "Excited", phonetic: "/ɪkˈsaɪtɪd/", category: "emotion" },
  { chinese: "平静", english: "Calm", phonetic: "/kɑːm/", category: "emotion" },
  { chinese: "紧张", english: "Nervous", phonetic: "/ˈnɜːvəs/", category: "emotion" },
  { chinese: "害羞", english: "Shy", phonetic: "/ʃaɪ/", category: "emotion" }
];

window.vocabularyList = vocabularyList;